/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        twitter: "#1da1f2",
        youtube: "#ff0000",
        github: "#333",
        facebook: "#1877f2",
        "base-600": "#616161",
      },
      boxShadow: {
        "inner-y":
          "inset 0 11px 8px -10px rgb(0 0 0 / 0.1), inset 0 -11px 8px -10px rgb(0 0 0 / 0.1)",
        "inner-t": "inset 0 11px 8px -10px rgb(0 0 0 / 0.1)",
        "inner-b": "inset 0 -11px 8px -10px rgb(0 0 0 / 0.1)",
      },
      height: {
        fs12: "12rem",
        fs18: "18rem",
        fs24: "24rem",
        fs32: "32rem",
        fs36: "36rem",
        v30: "30vh",
        v50: "50vh",
      },
      maxHeight: {
        v90: "90vh",
      },
      width: {
        fs12: "12rem",
        fs18: "18rem",
        fs24: "24rem",
        fs32: "32rem",
        fs36: "36rem",
        v30: "30vw",
        v50: "50vw",
      },
      maxWidth: {
        v50: "50vw",
        v60: "60vw",
      },
      animation: {
        "spin-slow": "spin 2s linear infinite",
      },
      scale: {
        flip: "-1",
      },
      borderColor: ({ theme }) => ({
        ...theme("colors"),
        DEFAULT: theme("colors.base-200", "currentColor"),
      }),
    },
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        snow: {
          primary: "#374151",
          secondary: "#71717a",
          accent: "#15803d",
          neutral: "#181A2A",
          info: "#1e3a8a",
          success: "#15803d",
          warning: "#b97808",
          error: "#b91c1c",
          "neutral-content": "#edf2f7",
          "base-100": "#ffffff",
          "base-200": "#e6e6e6",
          "base-300": "#cfcfcf",
          "base-content": "#181a2a",
          "--rounded-box": "0.25rem",
          "--rounded-btn": ".2rem",
          "--rounded-badge": ".125rem",
          "--animation-btn": "0",
          "--animation-input": "0",
          "--btn-focus-scale": "1",
          "--btn-text-case": "none",
        },
      },
      {
        obsidian: {
          primary: "#545252",
          secondary: "#545252",
          accent: "#545252",
          "base-100": "#000000",
          "base-200": "#1D1D1D",
          "base-300": "#1A1919",
          neutral: "#272626",
          "neutral-focus": "#343232",
          info: "#0000ff",
          success: "#008000",
          warning: "#ffff00",
          error: "#ff0000",
          "--rounded-box": "0.25rem",
          "--rounded-btn": ".2rem",
          "--rounded-badge": ".125rem",
          "--animation-btn": "0",
          "--animation-input": "0",
          "--btn-focus-scale": "1",
          "--btn-text-case": "none",
        },
      },
      {
        ocean: {
          primary: "#1e3a8a",
          secondary: "#71717a",
          accent: "#15803d",
          neutral: "#181A2A",
          info: "#1e3a8a",
          success: "#15803d",
          warning: "#b97808",
          error: "#b91c1c",
          "neutral-content": "#edf2f7",
          "base-100": "#eff6ff",
          "base-200": "#bfdbfe",
          "base-300": "#cfcfcf",
          "base-content": "#101c44",
          "--rounded-box": "0.25rem",
          "--rounded-btn": ".2rem",
          "--rounded-badge": ".125rem",
          "--animation-btn": "0",
          "--animation-input": "0",
          "--btn-focus-scale": "1",
          "--btn-text-case": "none",
        },
      },
      {
        sakura: {
          primary: "#7f1d1d",
          secondary: "#71717a",
          accent: "#15803d",
          neutral: "#181A2A",
          info: "#1e3a8a",
          success: "#15803d",
          warning: "#b97808",
          error: "#b91c1c",
          "neutral-content": "#edf2f7",
          "base-100": "#fef2f2",
          "base-200": "#fecaca",
          "base-300": "#cfcfcf",
          "base-content": "#3f1d1d",
          "--rounded-box": "0.25rem",
          "--rounded-btn": ".2rem",
          "--rounded-badge": ".125rem",
          "--animation-btn": "0",
          "--animation-input": "0",
          "--btn-focus-scale": "1",
          "--btn-text-case": "none",
        },
      },
      {
        forest: {
          primary: "#064e3b",
          secondary: "#71717a",
          accent: "#15803d",
          neutral: "#181A2A",
          info: "#1e3a8a",
          success: "#15803d",
          warning: "#b97808",
          error: "#b91c1c",
          "neutral-content": "#edf2f7",
          "base-100": "#f0fdf4",
          "base-200": "#65E092",
          "base-300": "#cfcfcf",
          "base-content": "#043025",
          "--rounded-box": "0.25rem",
          "--rounded-btn": ".2rem",
          "--rounded-badge": ".125rem",
          "--animation-btn": "0",
          "--animation-input": "0",
          "--btn-focus-scale": "1",
          "--btn-text-case": "none",
        },
      },
      {
        antique: {
          primary: "#78350f",
          secondary: "#71717a",
          accent: "#15803d",
          neutral: "#181A2A",
          info: "#1e3a8a",
          success: "#15803d",
          warning: "#b97808",
          error: "#b91c1c",
          "neutral-content": "#edf2f7",
          "base-100": "#fef3c7",
          "base-200": "#eab308",
          "base-300": "#cfcfcf",
          "base-content": "#351706",
          "--rounded-box": "0.25rem",
          "--rounded-btn": ".2rem",
          "--rounded-badge": ".125rem",
          "--animation-btn": "0",
          "--animation-input": "0",
          "--btn-focus-scale": "1",
          "--btn-text-case": "none",
        },
      },
    ],
  },
};
